name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fe tch noir-json-parser repo
        uses: actions/checkout@v2

      - name: Fetch tests repo
        run: |
          cd ../
          git clone https://github.com/rontosoft/noir-json-parser-tests.git tests
          mv noir-json-parser lib

      - name: Install nargo 0.13.0
        run: |
          cd ../
          url="https://github.com/noir-lang/noir/releases/download/nightly-2023-09-23/nargo-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$url" | tar -xz -C .
          chmod +x nargo

      - name: Run nargo tests
        run: |
          cd ../tests
          ../nargo test --show-output
